/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f401xx.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(){
	for(int i=0;i<1000000;i++);
}

int main(void)
{
	RCC->AHB1ENR |= (1<<0);
	GPIOA->MODER|=(1<<(2*2));
	GPIOA->MODER|=(1<<(2*3));
	GPIOA->MODER|=(1<<(2*4));
	GPIOA->ODR|=(1<<2);
	while(1){
		delay();
		GPIOA->ODR&=(0<<2);
		GPIOA->ODR|=(1<<3);
		delay();
		GPIOA->ODR&=(0<<3);
		GPIOA->ODR|=(1<<4);
		delay();
		GPIOA->ODR&=(0<<4);
		GPIOA->ODR|=(1<<2);
	}
}
